# Pandas

In [1]:
# Def: Pandas is a open source python library designed for data manipulation and analysis.

# Pandas is designed over the Numpy.

# Important operations in Pandas:
1. Data structures creation ( Series, DataFrame)
2. Data Input and Output (CSV, Excel, SQL, JSON)
3. Understand the dataset using pandas
4. Data Filtering and Indexing (loc and iloc)
5. Handling Missing values (Null values)
6. Handling Duplicate values
7. Handling inconsistant data
8. Data transformation using apply(), map()
9. Aggregation and grouping 
10. Time series data generation
11. Data visualization

# Installation and importing of pandas

In [2]:
# pip install pandas

# conda install pandas

import pandas as pd

In [3]:
pd.__version__

'2.2.3'

# 1. Data structures creation ( Series, DataFrame)

# Series : 1D array

In [4]:
# Def: Series is 1D Homogeneous array in pandas.

In [5]:
# creation of series : Empty series
ser1 = pd.Series()
print(ser1)
print(type(ser1))

Series([], dtype: object)
<class 'pandas.core.series.Series'>

In [6]:
# example-2 
salary = [50.5, 40.6, 60.1, 70.0, 80, 100, "Hello"]

ser2 = pd.Series(salary)
print(ser2)
print(type(ser2))

# Series automatically add the indexing of elements
# in pandas strings are represented as object

0     50.5
1     40.6
2     60.1
3     70.0
4       80
5      100
6    Hello
dtype: object
<class 'pandas.core.series.Series'>

In [7]:
# Series of strings

Movies = ["Spiderman", "Puspa", "Devara", "Salaar", "Kalki"]

ser2 = pd.Series(Movies, index = ["A", "B", "C", "D", "E"])
print(ser2)
print(type(ser2))

A    Spiderman
B        Puspa
C       Devara
D       Salaar
E        Kalki
dtype: object
<class 'pandas.core.series.Series'>

In [8]:
ser2[3]

C:\Users\Prikshit_Ishi\AppData\Local\Temp\ipykernel_18040\1801101107.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[3]

'Salaar'

In [9]:
# Negative indexing is not allowed on pandas Series
ser2[-2]

C:\Users\Prikshit_Ishi\AppData\Local\Temp\ipykernel_18040\4063792811.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-2]

'Salaar'

In [10]:
# create the pandas series from dictionary
d = {"Puri" : 40, "Dosa" : 60, "Idli" : 30}

ser2 = pd.Series(d)
print(ser2)
print(type(ser2))

Puri    40
Dosa    60
Idli    30
dtype: int64
<class 'pandas.core.series.Series'>

In [11]:
# convert the tuple into pandas series
tuple1 = (10, 20, 30, 40, 50)
ser3 = pd.Series(tuple1)
print(ser3)

0    10
1    20
2    30
3    40
4    50
dtype: int64

# We cannot convert set into pandas series
# set is unordered and pandas is ordered, so conversion not possible
set1 = {10, 20, 30, 40, 50}
ser3 = pd.Series(set1)
print(ser3)

In [12]:
# creating single element pandas series
ser4 = pd.Series(100)
print(ser4)

0    100
dtype: int64

# Update, delete, insert operations on Series

In [13]:
ser5 = pd.Series([10, 20, 30, 40, 50])
print(ser5)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [14]:
# update operation
ser5[3] = 99
print(ser5)

0    10
1    20
2    30
3    99
4    50
dtype: int64

In [15]:
# insert operation
# if index don't exist then new element will be inserted
ser5[5] = 999
print(ser5)

0     10
1     20
2     30
3     99
4     50
5    999
dtype: int64

In [16]:
# we can insert the element with any new index value
# index value need not be in sequence
ser5[10] = 99999
print(ser5)

0        10
1        20
2        30
3        99
4        50
5       999
10    99999
dtype: int64

In [17]:
ser5['A'] = 1000
print(ser5)

0        10
1        20
2        30
3        99
4        50
5       999
10    99999
A      1000
dtype: int64

In [18]:
ser5['A'] = 5000
print(ser5)

0        10
1        20
2        30
3        99
4        50
5       999
10    99999
A      5000
dtype: int64

In [19]:
# Delete element from Series
ser5 = ser5.drop(10)
print(ser5)

0      10
1      20
2      30
3      99
4      50
5     999
A    5000
dtype: int64

In [20]:
# Multiple elements deletion
ser5 = ser5.drop([1,2,3,5])
print(ser5)

0      10
4      50
A    5000
dtype: int64

In [21]:
ser5 = ser5.drop('A')
print(ser5)

0    10
4    50
dtype: int64

# DataFrame : 2D array

In [22]:
# Example-1 : creating empty dataframe

df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [23]:
Reel_count = [20, 35, 1000, 40, 19, 100, 200, 300]

df = pd.DataFrame(Reel_count)
print(df)
print(type(df))

      0
0    20
1    35
2  1000
3    40
4    19
5   100
6   200
7   300
<class 'pandas.core.frame.DataFrame'>

In [24]:
Reel_count = [[20, 35, 1000], [40, 19, 100],[ 200, 300,400]]

fruits_price = [["Seb", 150],["AragtiPandu", 70],["Mamidikaay", 80]]

df = pd.DataFrame(fruits_price, columns = ["Fruit Name", "Price"])
print(df)
print(type(df))

    Fruit Name  Price
0          Seb    150
1  AragtiPandu     70
2   Mamidikaay     80
<class 'pandas.core.frame.DataFrame'>

In [25]:
import pandas as pd

In [30]:
# Convert the dictionary to DataFrame
fruits_price = {"Seb": [150, 200, 300],"AragtiPandu": [70,80,90],"Mamidikaay": [80,90, 100]}

df = pd.DataFrame(fruits_price)
print(df)

# Key will become the column name
# Value will be inserting in that column

   Seb  AragtiPandu  Mamidikaay
0  150           70          80
1  200           80          90
2  300           90         100

In [31]:
# Convert a tuple of tuple into DataFrame

fruits_price = (("Seb", 150),("AragtiPandu", 70),("Mamidikaay", 80))
df = pd.DataFrame(fruits_price, columns = ["Fruit Name", "Price"])
print(df)
print(type(df))

    Fruit Name  Price
0          Seb    150
1  AragtiPandu     70
2   Mamidikaay     80
<class 'pandas.core.frame.DataFrame'>

In [35]:
# convert a set of set into DataFrame
# We CANNOT store the set inside the set
# We cannot store the Mutable items inside the set
fruits_price = [("Seb", 150),("AragtiPandu", 70),("Mamidikaay", 80)]
df = pd.DataFrame(fruits_price, columns = ["Fruit Name", "Price"])
print(df)
print(type(df))

    Fruit Name  Price
0          Seb    150
1  AragtiPandu     70
2   Mamidikaay     80
<class 'pandas.core.frame.DataFrame'>

In [36]:
# We can convert list of list into dataframe
# We can convert list of tuple into dataframe
# We can convert Tuple of tuple into Dataframe
# We cannot store set inside the set.
# We can convert set of tuple into datframe

In [42]:
# Converting a Series into dataframe
ser1 = pd.Series([10, 20, 30, 40])

df = pd.DataFrame(ser1, columns = ["Values"])
print(df)
print(type(df))

   Values
0      10
1      20
2      30
3      40
<class 'pandas.core.frame.DataFrame'>

# 2. importing and Exporting files data into DataFrame (CSE, Excel, SQL, JSON)

In [43]:
# Store the CSV and Excel file into Current working directory
import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [45]:
# importing CSV file data into dataframe
df_csv = pd.read_csv("csv_data.csv")
df_csv

       Name   Age         Profession  Salary                    Favorite Quote
0      John  25.0  Software Engineer   80000            Keep calm and code on!
1     Alice   NaN             Doctor  120000           Trust me, I'm a doctor!
2     Rocky   NaN              Boxer   50000                 Eye of the tiger!
3  Sherlock  40.0          Detective  150000  It's elementary, my dear Watson.
4  Mr. Bean  50.0           Comedian   10000                   Why so serious?
5  Mr. Bean  50.0           Comedian   10000                   Why so serious?

In [46]:
df_excel = pd.read_excel("excel_data.xlsx")
df_excel

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [48]:
# Export DataFrame data to Excel file
df_excel.to_excel("Da23_excel.xlsx")

In [49]:
# Export DataFrame data to  CSV file
df_csv.to_csv("Da23_csv.xlsx")

# import/Export the data from SQL database

In [2]:
import pandas as pd

In [3]:
# creating SQL database
import sqlite3  # library used for light weight sql database creation
conn = sqlite3.connect("DA23_Database.db")  

# connect() function help to connect with database
# if database don't exist then create new database

In [4]:
import os
os.getcwd()

'C:\\Users\\Prikshit_Ishi\\Complete_Data_Science\\Pandas'

In [6]:
df = pd.read_excel("excel_data.xlsx")

# to_sql : create the table and write the df data 
df.to_sql("table_data", conn, if_exists = "replace")

# to_sql() function create the table "table_data"
# conn : is the connection with our database
# if_exists : replace table if already exist

500

In [7]:
# Export data from table
exported_data = pd.read_sql("Select * From table_data", conn)
exported_data

,index,ID,Name,Age,Profession,salary,Marriage_proposal_count
0,0,1,olivia,23.0,Teacher,184518,0
1,1,2,sophia,20.0,Boxer,119572,2
2,2,3,jake,38.0,Scientist,174897,1
3,3,4,Rocky,56.0,Chef,117920,2
4,4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...,...
495,495,496,John,45.0,Boxer,137929,0
496,496,497,Sherlock,46.0,Boxer,39870,6
497,497,498,Sherlock,47.0,Detective,165951,5
498,498,499,Olivia,55.0,Comedian,192618,5
499,499,500,Sherlock,59.0,Software Engineer,194886,28

# import and Export data from JSON

In [8]:
# JSON is a dictionary type format data
# JSON is popularly used for sending and receving data from client to server

In [9]:
# read the data from json file
df = pd.read_json("json_data.json")
df

,order_id,customer_name,food_item,delivery_boy,rating,delivery_time_min
0,101,Ramu,Idli Burger,Speed Shankar,5,15
1,102,Priya,Dosa Pizza,Late Laxman,2,60
2,103,Dinesh,Paneer Sambar,Turbo Thambi,4,25
3,104,Lachu,Mango Maggi,Round Robin,1,90
4,105,Meena,Coconut Coffee,Careless Kannan,3,40

In [10]:
df.to_json("DA23_J_data.json")

# Understand the dataset using pandas

In [11]:
df = pd.read_excel("excel_data.xlsx")
df

      ID       Name   Age         Profession  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [12]:
df.shape

(500, 6)

In [13]:
# Head() shows the first 5 rows by default
df.head()

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1

In [14]:
# showing first 10 rows
df.head(10)

   ID       Name   Age   Profession  salary  Marriage_proposal_count
0   1     olivia  23.0      Teacher  184518                        0
1   2  sophia     20.0        Boxer  119572                        2
2   3       jake  38.0    Scientist  174897                        1
3   4      Rocky  56.0         Chef  117920                        2
4   4      Rocky  56.0         Chef  117920                        1
5   4      Rocky  56.0         Chef  117920                        3
6   4      Rocky  56.0         Chef  117920                       11
7   4      Rocky  56.0         Chef  117920                        2
8   4      Rocky  56.0         Chef  117920                        2
9   4      Rocky  56.0         Chef  117920                        3

In [15]:
# tail() function shows the last 5 rows by default
df.tail()

      ID      Name   Age         Profession  salary  Marriage_proposal_count
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [16]:
df.tail(8)

      ID      Name   Age         Profession  salary  Marriage_proposal_count
492  493      John  55.0             Artist   57720                        2
493  494    Sophia  39.0             Doctor  174500                        0
494  495     Rocky  27.0             Doctor   46975                        0
495  496      John  45.0              Boxer  137929                        0
496  497  Sherlock  46.0              Boxer   39870                        6
497  498  Sherlock  47.0          Detective  165951                        5
498  499    Olivia  55.0           Comedian  192618                        5
499  500  Sherlock  59.0  Software Engineer  194886                       28

In [17]:
# Printing specific column
df.Name

0         olivia
1      sophia
2           jake
3          Rocky
4          Rocky
         ...
495         John
496     Sherlock
497     Sherlock
498       Olivia
499     Sherlock
Name: Name, Length: 500, dtype: object

In [18]:
df.Profession

0                Teacher
1                  Boxer
2              Scientist
3                   Chef
4                   Chef
             ...
495                Boxer
496                Boxer
497            Detective
498             Comedian
499    Software Engineer
Name: Profession, Length: 500, dtype: object

In [22]:
# accessing multiple columns
df[['Name', 'Profession', 'Age']]

          Name         Profession   Age
0       olivia            Teacher  23.0
1    sophia                 Boxer  20.0
2         jake          Scientist  38.0
3        Rocky               Chef  56.0
4        Rocky               Chef  56.0
..         ...                ...   ...
495       John              Boxer  45.0
496   Sherlock              Boxer  46.0
497   Sherlock          Detective  47.0
498     Olivia           Comedian  55.0
499   Sherlock  Software Engineer  59.0

[500 rows x 3 columns]

# Renaming the column name

In [23]:
# printing just column names
df.columns

Index(['ID', 'Name', 'Age', 'Profession', 'salary', 'Marriage_proposal_count'], dtype='object')

In [24]:
rename_column = df.rename(columns = {'Profession' : 'Vruti'})
rename_column

      ID       Name   Age              Vruti  salary  Marriage_proposal_count
0      1     olivia  23.0            Teacher  184518                        0
1      2  sophia     20.0              Boxer  119572                        2
2      3       jake  38.0          Scientist  174897                        1
3      4      Rocky  56.0               Chef  117920                        2
4      4      Rocky  56.0               Chef  117920                        1
..   ...        ...   ...                ...     ...                      ...
495  496       John  45.0              Boxer  137929                        0
496  497   Sherlock  46.0              Boxer   39870                        6
497  498   Sherlock  47.0          Detective  165951                        5
498  499     Olivia  55.0           Comedian  192618                        5
499  500   Sherlock  59.0  Software Engineer  194886                       28

[500 rows x 6 columns]

In [26]:
# renaming multiple columns
rename_column = df.rename(columns = {'Profession' : 'Vruti', 'Name' : 'Peru', 'Age' : 'Vayasu', 'salary' : 'jitam'})
rename_column

,ID,Peru,Vayasu,Vruti,jitam,Marriage_proposal_count
0,1,olivia,23.0,Teacher,184518,0
1,2,sophia,20.0,Boxer,119572,2
2,3,jake,38.0,Scientist,174897,1
3,4,Rocky,56.0,Chef,117920,2
4,4,Rocky,56.0,Chef,117920,1
...,...,...,...,...,...,...
495,496,John,45.0,Boxer,137929,0
496,497,Sherlock,46.0,Boxer,39870,6
497,498,Sherlock,47.0,Detective,165951,5
498,499,Olivia,55.0,Comedian,192618,5
499,500,Sherlock,59.0,Software Engineer,194886,28